[pytest]
python_files = test_string_utils.py

markers =
    positive: только позитивные тесты
    negative: только неготивные тесты
    capitalize_test: тесты делает первую букву заглавной и возвращает этот же текст
    trim_test: тесты на удаление пробелов в начале строки
    contains_test: тесты на содержит ли искомый символ строка
    delete_symbol_test: тесты на удаляет все подстроки из переданной строки
